# Site settings
baseURL = "https://www.radlerhalle.de"
languageCode = "de-de"
title = "Radlerhalle in Karlsruhe"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Copyright
copyright = "&copy;2018 Martin Hauge, Yuji Kimura, Sebastian Lindler"

[params]

  # Metadata for search engines and social sharing
  author = "Martin Hauge, Yuji Kimura, Sebastian Lindler"
  description = "Radlerhalle in Karlsruhe"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "radlerhalle.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Hier gehts weiter.."

      [[params.links.list1.link]]
        text = "SeLi Rahmenbau"
        url = "https://seli-rahmenbau.de"

      [[params.links.list1.link]]
        text = "klovesradeln"
        url = "http://klovesradeln.de"

      [[params.links.list1.link]]
        text = "Radler Martin"
        url = "http://radlermartin.de"


  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split

